
####  DONE
POST http://localhost:5000/api/categories
Content-Type: application/json

{
    "name": "dcefdvvdvvefcd"
}

### DONE

GET http://localhost:5000/api/categories

### DONE

POST http://localhost:5000/api/tasks
Content-Type: application/json

{
    "task": "dharun",
    "priority": "high",
    "category": "EDUCATION"
}

### DONE


GET http://localhost:5000/api/tasks

### DONE


GET http://localhost:5000/api/tasks/18

### DONE

PUT http://localhost:5000/api/tasks/22
Content-Type: application/json

{
    "task": "dhasccsrun",
    "priority": "Medium",
    "category": "EDUCATION"
}

### DONE

PUT http://localhost:5000/api/categories/22
Content-Type: application/json

{
    "name": "dcefdvvdvvefcd"
}
### DONE

PUT http://localhost:5000/api/tasks/status/18

### DONE

DELETE http://localhost:5000/api/tasks/34

###

###

DELETE http://localhost:5000/api/categories/9

###
